spring:
  application:
    name: crud

  datasource:
    url: jdbc:postgresql://localhost:5432/crud
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    
    hibernate:
      ddl-auto: create-drop
      format_sql: true

server:
  port: 8082
